egift/adminportal/product/urls.py
from os import name
from django.urls import path
from .views import *
from generic.views import *

app_name = 'product_urls'

urlpatterns = [
    path('product_creation/', BaseCreateView.as_view(), name='product_creation'),
    path('update/<int:pk>', BaseUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', BaseDeleteView.as_view(), name='delete'),

    path('brand/', BrandCreateView.as_view(), name='brand'),
    path('update_brand/<int:pk>', UpdateBrandView.as_view(), name='update_brand'),
    path('delete_brand/<int:pk>', DeleteBrandView.as_view(), name='delete_brand'), 

    path('category/', CategoryCreateView.as_view(), name='category'),
    path('update_category/<int:pk>', UpdateCategoryView.as_view(), name='update_category'),
    path('delete_category/<int:pk>', DeleteCategoryView.as_view(), name='delete_category'),

    path('products/', CategoryBrandFilterView.as_view(), name='categories'), 
    path('single_product/<pk>', SingleProductView.as_view(),name='single_product'),
    path('search/', SearchView.as_view(), name='search'),

    
]

egift/adminportal/user/urls.py
from django.urls import path
from .views import * 
from . import views
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'user_urls'


urlpatterns = [
    path('', HomeView.as_view(),name='index'),
    path('admin_customized/', AdminHomeView.as_view(),name='admin_customized'),

    path('cart/',views.CartListView.as_view(),name='cart'),
    path('add_to_cart/',views.AddToCartView.as_view(),name='add_to_cart'),
    path('checkout/',views.CheckoutView.as_view(),name='checkout'),
    path('checkout-1/',AddressView.as_view(), name='address'),
    path('confirm/',EmailSendView.as_view(), name='email'),

    path('user_data/',AdminUserView.as_view(),name='user_data'),
    path('user_update/<int:pk>', UpdateUser.as_view(), name='user_update'),
    path('user_delete/<int:pk>', DeleteUser.as_view(), name='user_delete'),
    path('single_user/<pk>', UserDetailView.as_view(),name='single_user'),

    path('user-registration/',BaseRegisterView.as_view(), name='user_registration'),
    path('login/', LoginView.as_view(template_name='userportal/login.html', success_url = '/admin_customized/'), name='login'),
    path('logout/', LogoutView.as_view(template_name='userportal/login.html'), name='logout'),

    path('registration/',RegisterAdminUserView.as_view(), name='registration'),
    path('login-1/', AdminLoginView.as_view(), name='login_1'),
    path('logout-1/', LogoutView.as_view(template_name='adminportal/login.html'), name='logout_1'),

]

egift/egift/urls.py
from django.contrib import admin
from django.urls import path, include
from adminportal.user.views import *
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin_customized/', AdminHomeView.as_view(), name='admin_customized'),
    path('',include('adminportal.user.urls')),
    path ('',include('adminportal.product.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

egift/adminportal/product/forms.py
from django import forms

from .models import Brand, Category, Product

class ProductAddForm(forms.ModelForm):
    
    class Meta:
        model = Product
        fields = '__all__'
        exclude = ('is_deleted',)
        # widgets = {'name': forms.CharField(attrs = {'class': 'form-group',
        #                                             'id' : 'name',
        #                                             'name': 'product_name',})}
    # def clean_
class ProductBrandForm(forms.ModelForm):
    class Meta:
        model = Brand
        fields = ('name',)
    
class ProductCategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ('name',)

egift/adminportal/user/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import *
from adminportal.product.models import *

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    phone_number = forms.CharField(max_length=10)
    class Meta():
        model = User
        fields = ('username', 'password','email','phone_number','profile_pic')

class AdminForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    phone_number = forms.CharField(max_length=10)
    class Meta():
        model = User
        fields = ("username", "password", "email", "is_superuser", "is_staff", "is_active", "profile_pic", "phone_number",)

CHOICES = (
        ("H", "Home"),
        ("W", "Work"),
    )

class AddressForm(forms.ModelForm):
    user = forms.CharField(widget = forms.TextInput(attrs = {'name' : "user"}))
    address : forms.CharField(widget = forms.TextInput(attrs = {'name' : 'address'}))
    city_name : forms.CharField(widget = forms.TextInput(attrs = {'name' : "city_name"}))
    country_name : forms.CharField(widget = forms.TextInput(attrs = {'name' : "country_name"}))
    zip_code : forms.CharField(max_length=6,widget = forms.TextInput(attrs = {'name' : "zip_code"}))
    address_type =  forms.ChoiceField(choices=CHOICES)


    class Meta:
        model = Address
        fields = ("user",  "address", "city_name", "address_type", "country_name", "zip_code", )
        # widgets = {
        #             'address' : forms.Textarea(attrs = {'name' : 'address'}),
        #             'city_name' : forms.TextInput(attrs={'name' : 'city_name'}),
        #             'country_name' : forms.TextInput(attrs= {'name' : 'country_name'}),
        #             'zip_code' : forms.TextInput(attrs= {'name' : 'zip_code'}),
        #             'address_type' :  forms.RadioSelect(choices=[CHOICES])
        # }


# class UserProfileInfoForm(forms.ModelForm):
   
#     class Meta():
#         model = Customer
#         fields = ()
#         widgets = {}

egift/adminportal/product/views.py
from django.views.generic import  ListView

from .forms import *
from generic.views import *
# from ecommerce.adminportal.product.models import ProductImage
from django.db.models.query_utils import Q

# Create your views here.

#------------------------------Product-Brand------------------------------------#

class BrandCreateView(BaseCreateView, BaseAdminMixin):

    form_class = ProductBrandForm
    model = Brand
    template_name = "adminportal/brand.html"
    # success_url = '/admin_customized/'
    context_object_name = 'brand'

class UpdateBrandView(BaseAdminMixin, BaseUpdateView):

    model = Brand
    form_class = ProductBrandForm

class DeleteBrandView(BaseAdminMixin, BaseDeleteView):

    model = Brand


#------------------------------Product-Category------------------------------------#

class CategoryCreateView(BaseCreateView, BaseAdminMixin):

    form_class = ProductCategoryForm
    model = Category
    template_name = "adminportal/category.html"
    context_object_name = 'category'

class UpdateCategoryView(BaseAdminMixin, BaseUpdateView):

    model = Category
    form_class = ProductCategoryForm

class DeleteCategoryView(BaseAdminMixin,BaseDeleteView):

    model = Category

#------------------------------Product-Filter/Search/Single-Product------------------------------------#

class CategoryBrandFilterView(ListView):

    model = Product
    template_name = 'userportal/category.html'
    context_object_name = 'products'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["brand"] = Brand.objects.all()
        context["category"] = Category.objects.all()
        return context 

    def get_queryset(self):
        category = self.request.GET.get('category', None)
        brand = self.request.GET.get('brand', None)
        # category = get_object_or_404(Category, pk=self.kwargs['pk'])
        products = Product.objects.all()

        if category and not brand:
            products = products.filter(Q(category__name = category) )
        elif not category and brand:
            products = products.filter(Q(brand__name = brand))        
        elif category and brand:
            products = products.filter(Q(category__name = category) & Q(brand__name = brand))

        return products  

class SearchView(BaseListView):

    model = Product
    template_name = 'userportal/search.html'
    context_object_name = 'products'
    # context_object_name = 'q'

    def get_queryset(self):
        search = self.request.GET.get('q')
        print("search", search)
        if search:
            products = Product.objects.filter(Q(name__icontains=search ) | Q(price__icontains=search) |
                                             Q(brand__name__icontains=search) | Q(category__name__icontains=search)).order_by('created_at')
        else:
            products = Product.objects.none()
        return products

class SingleProductView(BaseDetailView):
    model = Product
    template_name = 'userportal/single_product.html'





 # def form_valid(self, form):
    #     product = form.save()
    #     if 'image' in request.FILES:
    #         ProductImage(
    #             product = product,
    #             image= image
    #         )
    #         product.image = request.FILES['image']
    #         ProductImage.save()
    #     return super().form_valid(form)

    # def post(self, request, *args, **kwargs):
    #     form = self.form_class(request.POST)
    #     if form.is_valid():
    #         product = form.save()
    #         if 'image' in request.FILES:
    #             product.image = request.FILES['image']
    #         product.save()
    #         registered = True
    #         messages.success(request, 'Product was created successfully!')

    #         return redirect('user_urls:admin_customized')

egift/adminportal/user/views.py
from django.db.models.query_utils import Q
from django.http import JsonResponse
from django.shortcuts import render
from django.views import View
from django.urls import reverse, reverse_lazy 
from django.views.generic import ListView
from generic.views import *
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from .models import *
from . import task
from adminportal.product.models import *



# Create BaseView For the below classes

#-----------------------------------User/Cart/Checkout-----------------------------------------#

class HomeView(ListView):

    context_object_name = 'items'
    model = Product
    # model = models.ProductImage
    template_name = 'userportal/index.html' 

class CartListView(BaseListView):

    model = CartItem
    template_name = 'userportal/cart.html'
    context_object_name = 'items'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["cart_total"] = CartItem(user = self.request.user)
        return context

    def get_queryset(self):
        user = User.objects.filter(username = self.request.user).first()
        print("user", user)
        queryset = CartItem.objects.filter(Q(user__username = user))
        return queryset
    
class AddToCartView(LoginRequiredMixin, View):

    def post(self, request, *args, **kwargs):

        item_id = request.POST.get('item_id')
        action = request.POST.get('action')
        quan = int(request.POST.get('quantity', 1))
        # print("quan", quan)
        try:
            product = Product.objects.get(id = item_id)
        except Exception as e:
            product = None

        user = User.objects.filter(username = request.user).first()
        # print("user", user)

        cart_item, created = CartItem.objects.get_or_create(user = user, product = product)
        print("CART_ITEM------->>>>", cart_item)
      
        cart_total = cart_item.get_cart_total
        get_cart_total = cart_item.get_total
        # print("Before cart_item_Total price", cart_item.quantity)

        if action == "add":
            if quan > 1:
                cart_item.quantity = cart_item.quantity + quan
                cart_total = cart_item.get_cart_total
            else:
                cart_item.quantity += 1
                cart_total = cart_item.get_cart_total

            cart_item.save()
        
        elif action == "remove":
            if cart_item.quantity <= 1:
                print("cart_item", cart_item)
                cart_item.delete()
                return JsonResponse({"product_total" : cart_total, "item_id":item_id, "get_cart_total" : get_cart_total}) 
            else:
                cart_item.quantity -= 1
                cart_total = cart_item.get_cart_total
                cart_item.save()

        elif action == "delete":
            cart_item.delete()
            return JsonResponse({"product_total" : cart_total, "item_id":item_id, "get_cart_total" : get_cart_total}) 

        # print("After cart item quan", cart_item.quantity)
        get_cart_total = cart_item.get_total
        cart_item.save()
        print("cart_item", cart_item)
        return JsonResponse({"product_total" : cart_total, "item_id":item_id, "get_cart_total" : get_cart_total}) 

class CheckoutView(BaseListView):

    model = CartItem
    # form_class = AddressForm
    template_name = 'userportal/checkout.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = User.objects.filter(username = self.request.user).first()
        print("user", user)
        context["products"] = CartItem.objects.filter(Q(user__username = user))
        context["cart_total"] = CartItem(user = self.request.user)
        return context
    
    def form_valid(self, form):
        user = self.request.user
        print("user", user)
        user = form.save()
        user.save()
        print("form-DAta___---------------->>>", form.cleaned_data)
        return super().form_valid(form)
    
    
    def get_queryset(self):

        user = User.objects.filter(username = self.request.user).first()
        print("user", user)
        products = CartItem.objects.filter(Q(user__username = user))
        print(products)
        return products

    def get_success_url(self):
        return reverse_lazy('user_urls:email')

class AddressView(FormView):
    model = Address
    form_class = AddressForm
    template_name = 'userportal/checkout.html'

    def form_valid(self, form):
        user = self.request.user
        print("user-1", user)
        # user_name = form.save()
        form.save()
        # user.save()
        print("form-DAta_-_-_-_-_-_-_-_-_-_>>>", form.cleaned_data , form.save())
        return super().form_valid(form)

    def form_invalid(self, form):
        print("form is in valid", form.errors)
        return super().form_invalid(form)

    def get_success_url(self):
        return reverse('user_urls:email')

class EmailSendView(View):

    def get(self, request, *args, **kwargs):
        print("inside post view")

        user = User.objects.filter(username = self.request.user).first()
        print(user, 'customer')

        carts = CartItem.objects.filter(Q(user__username = user))
        print('cart', carts)

        task.checkout(user_id=user.id)
        cart_total = CartItem(user = self.request.user)
        cart_total_1 = CartItem.objects.filter(user = user)
        print("cart_item--------------------??>>>>", cart_total_1, type(cart_total_1))
        cart_total_1.delete()
        print("cart----total", type(cart_total))
        context = {'carts': carts, 'cart_total' : cart_total}
        return render(request, 'userportal/confirmation.html', context)
#------------------------------------Admin-Side------------------------------------------#

class RegisterAdminUserView(BaseAdminMixin, BaseRegisterView):

    template_name = 'adminportal/registration.html'
    # success_message = "%(name)s was created successfully"
  
    def form_valid(self, form):
        user = form.save()
        user.set_password(user.password)
        user.is_superuser = True
        user.is_active = True
        user.is_staff = True   
        user.save()    
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('user_urls:login_1')
        
class AdminLoginView(LoginView):

    template_name='adminportal/login.html'

    def get_success_url(self):
        return reverse_lazy('user_urls:admin_customized')

class AdminHomeView(BaseAdminMixin, BaseListView):

    model = Product
    # model = models.ProductImage
    context_object_name = 'items'
    template_name = 'adminportal/index.html'

class AdminUserView(BaseAdminMixin, BaseListView):

    model = User 
    template_name = 'adminportal/user.html'
    context_object_name = 'user_data'   
        
class UserDetailView(BaseDetailView):

    model = User
    template_name = 'adminportal/single_user.html'


class UpdateUser(BaseUpdateView):

    model = User
    form_class = AdminForm
    template_name = 'adminportal/update.html'
    # success_message = "%(username)s was created successfully"

    def form_valid(self, form):
        user = form.save()
        user.set_password(user.password)   
        # user.save()    
        print("user is saving data")
        return super().form_valid(form)

    def get_success_message(self, cleaned_data):
        username = cleaned_data["username"]
        return username + " Updated Successfully..!!"
  
    def get_success_url(self):
        return reverse('user_urls:user_data')

class DeleteUser(BaseDeleteView):

    model = User
    template_name = 'userportal/proddel.html'
    context_object_name = 'delete_product'

    def get_success_message(self, cleaned_data):
        return "Deleted Successfully..!!"

    def get_success_url(self):
        return reverse('user_urls:user_data')

egift/templates/adminportal/_footer.html
<footer class="footer">
    <div class="d-sm-flex justify-content-center justify-content-sm-between">
      <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Premium <a href="https://www.bootstrapdash.com/" target="_blank">Bootstrap admin template</a> from BootstrapDash.</span>
      <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Copyright © 2021. All rights reserved.</span>
    </div>
  </footer>

egift/templates/adminportal/_sidebar.html
<nav class="sidebar sidebar-offcanvas" id="sidebar">
    <ul class="nav">
      <li class="nav-item">
        <a class="nav-link" href="index.html">
          <i class="mdi mdi-grid-large menu-icon"></i>
          <span class="menu-title">Dashboard</span>
        </a>
      </li>
      <li class="nav-item nav-category">UI Elements</li>
      <li class="nav-item">
        <a class="nav-link" data-bs-toggle="collapse" href="#ui-basic" aria-expanded="false" aria-controls="ui-basic">
          <i class="menu-icon mdi mdi-floor-plan"></i>
          <span class="menu-title">UI Elements</span>
          <i class="menu-arrow"></i> 
        </a>
        <div class="collapse" id="ui-basic">
          <ul class="nav flex-column sub-menu">
            <li class="nav-item"> <a class="nav-link" href="pages/ui-features/buttons.html">Buttons</a></li>
            <li class="nav-item"> <a class="nav-link" href="pages/ui-features/dropdowns.html">Dropdowns</a></li>
            <li class="nav-item"> <a class="nav-link" href="pages/ui-features/typography.html">Typography</a></li>
          </ul>
        </div>
      </li>
      <li class="nav-item nav-category">Forms and Datas</li>
      <li class="nav-item">
        <a class="nav-link" data-bs-toggle="collapse" href="#form-elements" aria-expanded="false" aria-controls="form-elements">
          <i class="menu-icon mdi mdi-card-text-outline"></i>
          <span class="menu-title">Form elements</span>
          <i class="menu-arrow"></i>
        </a>
        <div class="collapse" id="form-elements">
          <ul class="nav flex-column sub-menu">
            <li class="nav-item"><a class="nav-link" href="pages/forms/basic_elements.html">Basic Elements</a></li>
          </ul>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-bs-toggle="collapse" href="#charts" aria-expanded="false" aria-controls="charts">
          <i class="menu-icon mdi mdi-chart-line"></i>
          <span class="menu-title">Charts</span>
          <i class="menu-arrow"></i>
        </a>
        <div class="collapse" id="charts">
          <ul class="nav flex-column sub-menu">
            <li class="nav-item"> <a class="nav-link" href="pages/charts/chartjs.html">ChartJs</a></li>
          </ul>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-bs-toggle="collapse" href="#tables" aria-expanded="false" aria-controls="tables">
          <i class="menu-icon mdi mdi-table"></i>
          <span class="menu-title">Tables</span>
          <i class="menu-arrow"></i>
        </a>
        <div class="collapse" id="tables">
          <ul class="nav flex-column sub-menu">
            <li class="nav-item"> <a class="nav-link" href="pages/tables/basic-table.html">Basic table</a></li>
          </ul>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-bs-toggle="collapse" href="#icons" aria-expanded="false" aria-controls="icons">
          <i class="menu-icon mdi mdi-layers-outline"></i>
          <span class="menu-title">Icons</span>
          <i class="menu-arrow"></i>
        </a>
        <div class="collapse" id="icons">
          <ul class="nav flex-column sub-menu">
            <li class="nav-item"> <a class="nav-link" href="pages/icons/mdi.html">Mdi icons</a></li>
          </ul>
        </div>
      </li>
      <li class="nav-item nav-category">pages</li>
      <li class="nav-item">
        <a class="nav-link" data-bs-toggle="collapse" href="#auth" aria-expanded="false" aria-controls="auth">
          <i class="menu-icon mdi mdi-account-circle-outline"></i>
          <span class="menu-title">User Pages</span>
          <i class="menu-arrow"></i>
        </a>
        <div class="collapse" id="auth">
          <ul class="nav flex-column sub-menu">
            <li class="nav-item"> <a class="nav-link" href="pages/samples/login.html"> Login </a></li>
          </ul>
        </div>
      </li>
      <li class="nav-item nav-category">help</li>
      <li class="nav-item">
        <a class="nav-link" href="http://bootstrapdash.com/demo/star-admin2-free/docs/documentation.html">
          <i class="menu-icon mdi mdi-file-document"></i>
          <span class="menu-title">Documentation</span>
        </a>
      </li>
    </ul>
  </nav>

egift/templates/adminportal/brand.html
{% extends 'adminportal/base.html' %} {% load crispy_forms_tags %} {% load static %} {% block head %}
<title>Admin</title>
{% endblock %} {% block body_block %}

<!-- partial -->
<div class="main-panel">
    <div class="content-wrapper">
        <div class="row">
            <div class="col-lg-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Add Brand </h4>
                        <form class="form-row" method="POST" enctype="multipart/form-data">
                            {% csrf_token %} {{ form|crispy }}
                            <div class="mt-3">
                                <input class="btn btn-block btn-primary btn-lg font-weight-medium auth-form-btn" type="submit" name="Register" value="Register">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-lg-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Brand Table</h4>
                        <div class="table-responsive">
                            <table class="table table-striped">
                                <thead>
                                    <tr>
                                        <th>
                                            Brand ID
                                        </th>
                                        <th>
                                            Brand Name
                                        </th>
                                        <th>
                                            Brand <br> Edit/Delete
                                        </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for item in brand %}

                                    <tr>
                                        <td>
                                            {{item.id}}
                                        </td>
                                        <td>
                                            {{item.name}}
                                        </td>
                                        <td>
                                            <a href="{% url 'product_urls:update_brand' item.id %}" type="button" class="btn btn-warning" style="padding: 6px;">
                                                <span class="mdi mdi-grease-pencil"></span>
                                            </a>
                                            <a style="padding: 5px;"> </a>
                                            <a href="{% url 'product_urls:delete_brand' item.id %}" type="button" class="btn btn-danger" style="padding: 6px;">
                                                <span class="mdi mdi-delete-empty"></span>
                                            </a>
                                        </td>
                                    </tr>
                                    {% endfor %}

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

</div>
<!-- main-panel ends -->
{% endblock %} {% block scripts %} {% endblock %}

egift/templates/adminportal/proddel.html
{% extends 'adminportal/base.html' %} {% load static %} {% block head %}
<title>Admin</title>
{% endblock %} {% block body_block %}
<!-- partial -->
<div class="main-panel">
    <div class="content-wrapper">
        <div class="row">
            <div class="col-lg-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Delete Product ??</h4>
                        <form class="form-row" method="POST">
                            {% csrf_token %} You Sure Want to Delete the product : <b> {{ delete_product.name }} / {{ delete_product.price }}?? </b>
                            <div class="mt-3">
                                <input class="btn btn-danger" type="submit" value="Delete" />
                                <a href="{% url 'user_urls:admin_customized' %}"><input class="btn btn-primary" type="button" name="Cancel" value="Cancel" /> </a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- main-panel ends -->
{% endblock %} {% block scripts %} {% endblock %}

egift/templates/adminportal/user.html
{% extends 'adminportal/base.html' %} {% load static %} {% block head %}
<title>Admin</title>
{% endblock %} {% block body_block %}
<div class="main-panel">
    <div class="content-wrapper">
        <div class="row">

            <div class="col-lg-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title"><a style="margin-left: 85%;" class="btn btn-outline-primary float-left" href="{% url 'user_urls:registration' %}" type="button">Add User</a> Customer Table</h4>

                        <div class="table-responsive">
                            {% for message in messages %}
                            <div style="color:rgb(1, 9, 119);" class="alert alert-success alert-dismissible" role="alert">
                                {{ message }}
                            </div>
                            {% endfor %}
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>Image</th>
                                        <th>Name</th>
                                        <th>Email</th>
                                        <th>Number</th>
                                        <th>Edit/Delete </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% if user_data %} {% for prod in user_data %}
                                    <tr>
                                        <td><img src="{{ prod.profile_pic.url }}" alt=""></td>
                                        <td>{{prod.username}}</td>
                                        <td>{{prod.email}}</td>
                                        <td>{{prod.phone_number}}</td>
                                        <td>
                                            <a href="{% url 'user_urls:user_update' prod.id %}" type="button" class="btn btn-warning" style="padding: 6px;">
                                                <span class="mdi mdi-grease-pencil"></span>
                                            </a>
                                            <a style="padding: 5px;"> </a>
                                            <a href="{% url 'user_urls:user_delete' prod.id %}" type="button" class="btn btn-danger" style="padding: 6px;">
                                                <span class="mdi mdi-delete-empty"></span>
                                            </a>
                                        </td>
                                    </tr>
                                    {% endfor %} {% else %}
                                    <tr>
                                        <td>
                                            No Username Have Been Entered Yet..!!
                                        </td>
                                    </tr>
                                    {% endif %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %} {% block scripts %} {% endblock %}