egift/adminportal/product/urls.py
from os import name
from django.urls import path
from .views import *
from generic.views import *

app_name = 'product_urls'

urlpatterns = [
    path('product_creation/', BaseCreateView.as_view(), name='product_creation'),
    path('update/<int:pk>', BaseUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', BaseDeleteView.as_view(), name='delete'),

    path('brand/', BrandCreateView.as_view(), name='brand'),
    path('update_brand/<int:pk>', UpdateBrandView.as_view(), name='update_brand'),
    path('delete_brand/<int:pk>', DeleteBrandView.as_view(), name='delete_brand'), 

    path('category/', CategoryCreateView.as_view(), name='category'),
    path('update_category/<int:pk>', UpdateCategoryView.as_view(), name='update_category'),
    path('delete_category/<int:pk>', DeleteCategoryView.as_view(), name='delete_category'),

    path('products/', CategoryBrandFilterView.as_view(), name='categories'), 
    path('single_product/<pk>', SingleProductView.as_view(),name='single_product'),
    path('search/', SearchView.as_view(), name='search'),

    
]

egift/adminportal/user/urls.py
from django.urls import path
from .views import * 
from . import views
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'user_urls'


urlpatterns = [
    path('', HomeView.as_view(),name='index'),
    path('admin_customized/', AdminHomeView.as_view(),name='admin_customized'),

    path('cart/',views.CartListView.as_view(),name='cart'),
    path('add_to_cart/',views.AddToCartView.as_view(),name='add_to_cart'),
    path('checkout/',views.CheckoutView.as_view(),name='checkout'),
    path('checkout-1/',AddressView.as_view(), name='address'),
    path('confirm/',EmailSendView.as_view(), name='email'),

    path('user_data/',AdminUserView.as_view(),name='user_data'),
    path('user_update/<int:pk>', UpdateUser.as_view(), name='user_update'),
    path('user_delete/<int:pk>', DeleteUser.as_view(), name='user_delete'),
    path('single_user/<pk>', UserDetailView.as_view(),name='single_user'),

    path('user-registration/',BaseRegisterView.as_view(), name='user_registration'),
    path('login/', LoginView.as_view(template_name='userportal/login.html', success_url = '/admin_customized/'), name='login'),
    path('logout/', LogoutView.as_view(template_name='userportal/login.html'), name='logout'),

    path('registration/',RegisterAdminUserView.as_view(), name='registration'),
    path('login-1/', AdminLoginView.as_view(), name='login_1'),
    path('logout-1/', LogoutView.as_view(template_name='adminportal/login.html'), name='logout_1'),

]

egift/egift/urls.py
from django.contrib import admin
from django.urls import path, include
from adminportal.user.views import *
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin_customized/', AdminHomeView.as_view(), name='admin_customized'),
    path('',include('adminportal.user.urls')),
    path ('',include('adminportal.product.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

egift/templates/userportal/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx" class="no-js">

<head>
    <!-- Mobile Specific Meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Favicon-->
    <link rel="shortcut icon" href="{% static 'userportal/img/fav.png' %}">
    <!-- Author Meta -->
    <meta name="author" content="CodePixar">
    <!-- Meta Description -->
    <meta name="description" content="">
    <!-- Meta Keyword -->
    <meta name="keywords" content="">
    <!-- meta character set -->
    <meta charset="UTF-8">
    <!-- Site Title -->
    <title>TREASURE BOX</title>
    <!--
		CSS
		============================================= -->
    <link rel="stylesheet" href="{% static 'userportal/css/linearicons.css' %}">
    <link rel="stylesheet" href="{% static 'userportal/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'userportal/css/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'userportal/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'userportal/css/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'userportal/css/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'userportal/css/nouislider.min.css' %}">
    <link rel="stylesheet" href="{% static 'userportal/css/ion.rangeSlider.css' %}" />
    <link rel="stylesheet" href="{% static 'userportal/css/ion.rangeSlider.skinFlat.css' %}" />
    <link rel="stylesheet" href="{% static 'userportal/css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'userportal/css/main.css' %}">
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="{% static 'https://www.googletagmanager.com/gtag/js?id=G-JKMMT3PCN9' %}"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }
        gtag('js', new Date());

        gtag('config', 'G-JKMMT3PCN9');
    </script>
    {% block head %} {% endblock %}
</head>

<body>

    <!-- Start Header Area -->
    <header class="header_area sticky-header">
        <div class="main_menu">
            <nav class="navbar navbar-expand-lg navbar-light main_box">
                <div class="container">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    {% if user.is_superuser %}

                    <a href="{% url 'user_urls:admin_customized' %}" class="nav-link"><b> Admin </b></a> {% else %}
                    <a href="{% url 'user_urls:index' %}" class="nav-link">
                        <img class="fixed nav-item" src="{% static 'userportal/img/logo.png' %}" alt="">
                    </a>
                    {% endif %}

                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse offset" id="navbarSupportedContent">
                        <ul class="nav navbar-nav menu_nav ml-auto">
                            <li class="nav-item active"><a class="nav-link" href="{% url 'user_urls:index' %}">Home</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'user_urls:cart' %}">Cart</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'product_urls:categories' %}">Filter</a></li>

                            <!-- <li class="nav-item submenu dropdown">
                                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Shop</a>
                                <ul class="dropdown-menu">
                                    <li class="nav-item"><a class="nav-link" href="checkout.html">Product Checkout</a></li> 
                                    <li class="nav-item"><a class="nav-link" href="confirmation.html">Confirmation</a></li>
                                    <li class="nav-item"><a class="nav-link" href="{% url 'user_urls:cart' %}">Cart</a></li>
                                </ul>
                            </li>
                            <li class="nav-item submenu dropdown">
                                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Blog</a>
                                <ul class="dropdown-menu">
                                    <li class="nav-item"><a class="nav-link" href="blog.html">Blog</a></li>
                                    <li class="nav-item"><a class="nav-link" href="single-blog.html">Blog Details</a></li>
                                </ul>
                            </li> -->
                            {% if user.is_authenticated %}
                            <li class="nav-item"><a class="nav-link" href="{% url 'user_urls:logout' %}"><b> Log Out </b></a></li>

                            {% else %}
                            <li class="nav-item"><a class="nav-link" href="{% url 'user_urls:login' %}"><b>Log In</b></a></li>

                            {% endif %}
                            <li class="nav-item"><a class="nav-link" href="contact.html">Contact</a></li>
                        </ul>
                        <ul class="nav navbar-nav navbar-right">
                            <li class="nav-item"><a href="{% url 'user_urls:cart' %}" class="cart"><span class="ti-bag"></span></a></li>
                            <li class="nav-item"><button class="search"><span name="q" class="lnr lnr-magnifier" id="search"></span></button></li>
                        </ul>
                    </div>
                </div>
            </nav>
        </div>
        <div class="search_input" id="search_input_box">
            <div class="container">
                <form class="d-flex justify-content-between" action="{% url 'product_urls:search' %}">
                    <input type="text" name="q" class="form-control" id="search_input" placeholder="Search Here">
                    <button type="submit" class="btn"></button>
                    <span class="lnr lnr-cross" id="close_search" title="Close Search"></span>
                </form>
            </div>
        </div>
    </header>
    <!-- End Header Area -->
    {% block body_block %} {% endblock %}   

    <!-- start footer Area -->
    <footer class="footer-area section_gap">
        <div class="container">
            <div class="row">
                <div class="col-lg-3  col-md-6 col-sm-6">
                    <div class="single-footer-widget">
                        <h6>About Us</h6>
                        <p>
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore dolore magna aliqua.
                        </p>
                    </div>
                </div>
                <div class="col-lg-4  col-md-6 col-sm-6">
                    <div class="single-footer-widget">
                        <h6>Newsletter</h6>
                        <p>Stay update with our latest</p>
                        <div class="" id="mc_embed_signup">

                            <form target="_blank" novalidate="true" action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01" method="get" class="form-inline">

                                <div class="d-flex flex-row">

                                    <input class="form-control" name="EMAIL" placeholder="Enter Email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Email '" required="" type="email">


                                    <button class="click-btn btn btn-default"><i class="fa fa-long-arrow-right" aria-hidden="true"></i></button>
                                    <div style="position: absolute; left: -5000px;">
                                        <input name="b_36c4fd991d266f23781ded980_aefe40901a" tabindex="-1" value="" type="text">
                                    </div>

                                    <!-- <div class="col-lg-4 col-md-4">
												<button class="bb-btn btn"><span class="lnr lnr-arrow-right"></span></button>
											</div>  -->
                                </div>
                                <div class="info"></div>
                            </form>
                        </div>
                    </div>
                </div>
                <!-- <div class="col-lg-3  col-md-6 col-sm-6">
                    <div class="single-footer-widget mail-chimp">
                        <h6 class="mb-20">Instragram Feed</h6>
                        <ul class="instafeed d-flex flex-wrap">
                            <li><img src="img/i1.jpg" alt=""></li>
                            <li><img src="img/i2.jpg" alt=""></li>
                            <li><img src="img/i3.jpg" alt=""></li>
                            <li><img src="img/i4.jpg" alt=""></li>
                            <li><img src="img/i5.jpg" alt=""></li>
                            <li><img src="img/i6.jpg" alt=""></li>
                            <li><img src="img/i7.jpg" alt=""></li>
                            <li><img src="img/i8.jpg" alt=""></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-2 col-md-6 col-sm-6">
                    <div class="single-footer-widget">
                        <h6>Follow Us</h6>
                        <p>Let us be social</p>
                        <div class="footer-social d-flex align-items-center">
                            <a href="#"><i class="fa fa-facebook"></i></a>
                            <a href="#"><i class="fa fa-twitter"></i></a>
                            <a href="#"><i class="fa fa-dribbble"></i></a>
                            <a href="#"><i class="fa fa-behance"></i></a>
                        </div>
                    </div>
                </div> -->
            </div>
            <div class="footer-bottom d-flex justify-content-center align-items-center flex-wrap">
                <p class="footer-text m-0">
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    Copyright &copy;
                    <script>
                        document.write(new Date().getFullYear());
                    </script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                </p>
            </div>
        </div>
    </footer>
    <!-- End footer Area -->

    <script src="{% static 'userportal/js/vendor/jquery-2.2.4.min.js' %}"></script>
    <script src="{% static 'latrtaropresustatichttps://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js' %}" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="{% static 'userportal/js/vendor/bootstrap.min.js' %}"></script>
    <script src="{% static 'userportal/js/jquery.ajaxchimp.min.js' %}"></script>
    <script src="{% static 'userportal/js/jquery.nice-select.min.js' %}"></script>
    <script src="{% static 'userportal/js/jquery.sticky.js' %}"></script>
    <script src="{% static 'userportal/js/nouislider.min.js' %}"></script>
    <script src="{% static 'userportal/js/countdown.js' %}"></script>
    <script src="{% static 'userportal/js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'userportal/js/owl.carousel.min.js' %}"></script>
    <!--gmaps Js-->
    <!-- <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCjCGmQ0Uq4exrzdcL6rvxywDDOvfAu6eE"></script> 
    <script src="{% static 'userportal/js/gmaps.min.js' %}"></script>-->
    <script src="{% static 'userportal/js/main.js' %}"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    {% block scripts %} {% endblock %}

</body>

</html>

egift/templates/userportal/cart.html
{% extends 'userportal/base.html' %} {% load static %} {% block head %}
<title>Admin</title>
{% endblock %} {% block body_block %}
<!-- partial -->

<section class="banner-area organic-breadcrumb">
    <div class="container">
        <div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
            <div class="col-first">
                <h1>Shopping Cart</h1>
                <nav class="d-flex align-items-center">
                    <a href="{% url 'user_urls:index' %}">Home<span class="lnr lnr-arrow-right"></span></a>
                    <a href="{% url 'product_urls:category' %}">Category</a>
                </nav>
            </div>
        </div>
    </div>
</section>
<div class="main-panel">
    <div class="content-wrapper">
        <div class="row" style="color:black; margin-left: 50px; margin-right: 50px; font-size: 16px;">
            <div class="col-lg-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <div class="table-responsive">

                            <table class="table" style="border: 200px;" id="cart">
                                <thead>
                                    <tr>
                                        <th>Product Image</th>
                                        <th>Product Name</th>
                                        <th>Product Price</th>
                                        <th>Product Add/Remove</th>
                                        <th>Product Total</th>
                                        <th>Remove Item</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% if items %} {% for prod in items %}
                                    <tr id="{{ prod.id }}">
                                        <td><img src="{{ prod.product.image.url }}" style="width:100px;height:100px;" alt=""></td>
                                        <td>{{prod.product.name}}</td>
                                        <td>{{prod.product.price}}</td>
                                        <td>
                                            <div class="pl-md-0 pl-2">
                                                <span id="mybtn" onclick="updateuserorder('{{ prod.product.id }}','add')" class="fa fa-plus-square text-secondary"></span>
                                                <!-- <span class="px-md-3 px-1" id="item_update{{ prod.product.id }}">{{ prod.quantity }}</span> -->
                                                <input id="item_update{{ prod.product.id }}" type="number" value="{{ prod.quantity }}" style="width:39px;height:30px;border: hidden;">
                                                <span id="mybtn" onclick="updateuserorder('{{ prod.product.id }}','remove')" class="fa fa-minus-square text-secondary"></span>

                                            </div>

                                            <!-- <i onclick="updateuserorder('{{ prod.product.id }}','add')" class="fa fa-plus-square text-secondary"></i>
                                            <input id="item_update{{ prod.product.id }}" type="number" value="{{ prod.quantity }}" title="Quantity:" style="width:30px;height:30px;border: hidden;">
                                            <i onclick="updateuserorder('{{ prod.product.id }}','remove')" class="fa fa-minus-square text-secondary"></i> -->
                                        </td>
                                        <td id="cart_total{{ prod.product.id }}" style="color:black;font-size: 16px;">{{ prod.get_cart_total }}</td>
                                        <td>
                                            <a type="button" class="btn btn-danger" style="padding: 6px; color: white;">
                                                <span onclick="updateuserorder('{{ prod.product.id }}','delete')" class="ti-trash"></span>
                                            </a>
                                        </td>
                                    </tr>
                                    {% endfor %} {% endif %}
                                    <tr>
                                        <td>
                                            <b>Sub-Total</b> </td>
                                        <td>
                                            <b>Tax(18%)</b> </td>
                                        <td>

                                        </td>
                                        <td>

                                        </td>
                                        <td id="get_cart_total">
                                            {{ cart_total.get_total }}
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>

                                        </td>
                                        <td>

                                        </td>
                                        <td>
                                            <div class="checkout_btn_inner d-flex align-items-center">
                                                <a class="gray_btn" href="{% url 'user_urls:index' %}">Continue Shopping</a>
                                                <a class="primary-btn" href="{% url 'user_urls:checkout' %}">Proceed to checkout</a>
                                            </div>
                                        </td>
                                    </tr>

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- content-wrapper ends -->

    <!-- partial -->
</div>
<!-- main-panel ends -->
{% endblock %} {% block scripts %}
<script>
    function updateuserorder(item_id, action) {


        console.log('item:', item_id);
        console.log('action', action)


        $.ajax({
            method: "POST",
            headers: {
                'X-CSRFToken': csrftoken
            },
            url: "{% url 'user_urls:add_to_cart' %}",
            data: {
                'action': action,
                'item_id': item_id
            },
            success: function(data) {
                // console.log(data.item_id)
                // console.log(data.product_total)
                // console.log(data.get_cart_total)

                var product_total = document.getElementById('cart_total' + item_id);
                product_total.innerHTML = data.product_total

                var whole_total = document.getElementById('get_cart_total')
                whole_total.innerHTML = data.get_cart_total

                var result = document.getElementById('item_update' + item_id);

                if (action == "add") {
                    if (!isNaN(result.value))
                        result.value++;

                } else if (action == "remove") {
                    if (result.value <= 1) {
                        location.reload()
                    } else if (!isNaN(result.value) && result.value > 0) {
                        result.value--;
                    }
                } else if (action == "delete") {
                    location.reload()

                }
            },
            error: function(error) {
                Swal.fire(
                    'Oops!',
                    'Something went wrong',
                    'error'
                )
            },

        })
    }


    function getCookie(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            const cookies = document.cookie.split(';');
            for (let i = 0; i < cookies.length; i++) {
                const cookie = cookies[i].trim();
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    const csrftoken = getCookie('csrftoken');
</script>
{% endblock %}

egift/templates/userportal/login.html
{% extends 'userportal/base.html' %} {% load static %} {% block head %}
<title>TREASSURE BOX</title>
{% endblock %} {% block body_block %}

<!-- Start Banner Area -->
<section class="banner-area organic-breadcrumb">
    <div class="container">
        <div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
            <div class="col-first">
                <h1>Login/Register</h1>
                <nav class="d-flex align-items-center">
                    <a href="{% url 'user_urls:index' %}">Home<span class="lnr lnr-arrow-right"></span></a>
                    <a href="#">Login/Register</a>
                </nav>
            </div>
        </div>
    </div>
</section>
<!-- End Banner Area -->

<!--================Login Box Area =================-->
<section class="login_box_area section_gap">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <div class="login_box_img">
                    <img class="img-fluid" src="{% static 'userportal/img/login1.jpg' %}" alt="">
                    <div class="hover">
                        <h4>New to our website?</h4>
                        <p>Make your loved ones happy with many special and exciting gifts</p>
                        <a class="primary-btn" href="{% url 'user_urls:user_registration' %}">Create an Account</a>
                    </div>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="login_form_inner">
                    <h3>Log in to enter</h3>
                    <div class="creat_account">
                        {% if form.errors %}
                        <div style="color:red;" class="alert alert-error alert-dismissible" role="alert">
                            Please Enter Valid Username/Password
                        </div>
                        {% endif %} {% for message in messages %}
                        <div style="color:rgb(1, 9, 119);" class="alert alert-success alert-dismissible" role="alert">
                            {{ message }}
                        </div>
                        {% endfor %}
                    </div>
                    <form class="row login_form" action="{% url 'user_urls:login' %}" method="post" id="contactForm" novalidate="novalidate">
                        {% csrf_token %}

                        <div class="col-md-12 form-group">
                            <input type="username" name="username" class="form-control" placeholder="Username" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Username'">
                        </div>
                        <div class="col-md-12 form-group">
                            <input type="password" name="password" class="form-control" placeholder="Password" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Password'">
                        </div>
                        <div class="col-md-12 form-group">
                            <div class="creat_account">
                                <input type="checkbox" id="f-option2" name="selector">
                                <label for="f-option2">Keep me logged in</label>
                            </div>
                        </div>
                        <div class="col-md-12 form-group">
                            <button type="submit" value="submit" class="primary-btn">Log In</button>
                            <a href="#">Forgot Password?</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
<!--================End Login Box Area =================-->
{% endblock %} {% block scripts %} {% endblock %}

egift/templates/userportal/proddel.html
{% extends 'adminportal/base.html' %} {% load static %} {% block head %}
<title>Admin</title>
{% endblock %} {% block body_block %}
<!-- partial -->
<div class="main-panel">
    <div class="content-wrapper">
        <div class="row">
            <div class="col-lg-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Delete User ??</h4>
                        <form class="form-row" method="POST">
                            {% csrf_token %} You Sure Want to Delete the User <br> Username: {{ delete_product.username }} <br> Email : {{ delete_product.email }}??
                            <div class="mt-3">
                                <input class="btn btn-danger" type="submit" value="Delete" />
                                <a href="{% url 'user_urls:index' %}"><input class="btn btn-primary" type="button" name="Cancel" value="Cancel" /> </a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- main-panel ends -->
{% endblock %} {% block scripts %} {% endblock %}

egift/templates/userportal/registration.html
{% extends 'userportal/base.html' %} {% load static %} {% load crispy_forms_tags %} {% block body_block %}
<!-- Start Banner Area -->
<section class="banner-area organic-breadcrumb">
    <div class="container">
        <div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
            <div class="col-first">
                <h1>Login/Register</h1>
                <nav class="d-flex align-items-center">
                    <a href="{% static 'userportal/index.html' %}">Home<span class="lnr lnr-arrow-right"></span></a>
                    <a href="{% url 'user_urls:login' %}">Login/Register</a>
                </nav>
            </div>
        </div>
    </div>
</section>
<!-- End Banner Area -->
<section class="login_box_area section_gap">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <div class="login_box_img">
                    <img class="img-fluid" src="{% static 'userportal/img/login.jpg' %}" alt="">
                    <div class="hover">
                        <h3 style="color: white;">Thank you for registering to our website.</h3>
                        <p>Laughter is the best medicine in the world.</p>
                        <a class="primary-btn" href="{% url 'user_urls:login' %}">Already have an Account ?</a>
                    </div>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="login_form_inner" style="text-align: start;padding-top: 15px; padding-left: 15px;">
                    <h1 style="text-align: center;">Register Here!</h1>
                    <h3 style="text-align: center;">Fill out the form: </h3>
                    <form class="uniForm" method="POST" enctype="multipart/form-data">
                        {% csrf_token %} {{ form|crispy }}
                        <div class="mt-3">
                            <input class="uniForm btn btn-block btn-primary btn-lg font-weight-medium auth-form-btn" type="submit" name="Register" value="Register">
                        </div>
                    </form>
                </div>

            </div>
        </div>
    </div>
</section>
<!-- <div class="col">
    <div class="login_form_inner">

        <h1>Register Here!</h1>
        <h3>Fill out the form: </h3>

        <form class="uniForm" method="POST" enctype="multipart/form-data">
            {% csrf_token %} {{ form|crispy }}
            <input class="btn-primary" type="submit" name="Register" value="Register">
        </form>


    </div>
</div> -->


{% endblock %} {% block scripts %} {% endblock %}